### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by lfarah** [D-32/MiniTabBar#1]
Hey, your library is really interesting.

The only problem I found was the ```README.md```, which lacks information.
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to better organize.
If you want, I can help you to do it.

What are your thoughts?

**Comment by lfarah** [comment]
Please fix this before we can [approve this PR](https://github.com/vsouza/awesome-ios/pull/1399)

**Comment by D-32** [comment]
@lfarah: I've updated the readme, let me know if this matches your expectations. Otherwise let me know what specifically you're missing.

**Comment by lfarah** [comment]
Perfect!
