### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by rhanb** [D-32/MiniTabBar#5]
Hi,

Love this small library thanks for this work! 
Do you plan to implement new features? Those ones would be great:

- Add badge / notification  to an item
- Allow to keep the text on the bottom of an item when selected (like this [library](https://github.com/aurelhubert/ahbottomnavigation) in android with "title states"
- Smooth hide/show transition

**Comment by D-32** [comment]
Currently not planning on adding these features. PR are always welcome though :)

**Comment by rhanb** [comment]
Ok ! Working on it, badges almost done 😄 

(I'm building a [plugin](https://github.com/rhanbIT/nativescript-bottombar) for NativeScript, I'm going to implement a version for iOS using your library if you want to check this out!)
